<AutomaticThreadingBar>:
  orientation: "horizontal"
  size_hint_y: None
  height: 128

  Button:
    width: 96
    size_hint_x: None
    text: "Stop" if root.is_running else "Start"
    font_size: self.height / 4
    font_style: "bold"
    background_color: [1, 0.2, 0.2, 1] if root.is_running else [0.3, 0.3, 0.3, 1]
    on_release: root.toggle_is_running()

  BoxLayout:
    orientation: "vertical"
    size_hint_x: 0.8
    Label:
      text: "Current"
      text_size: self.size
      size_hint_y: 0.15
      font_size: 16
      color: app.display_color
      halign: 'center'
      valign: 'top'
    Button:
      size_hint_y: 0.30
      font_name: "fonts/iosevka-regular.ttf"
      font_size: self.height / 2
      font_style: "bold"
      background_color: [0.2, 0.2, 0.2, 1]
      color: app.formats.display_color
      text: app.servo.formattedPosition
      text_size: self.size
      halign: 'center'
      valign: 'middle'
      disabled: app.servo.disableControls
      on_release: app.servo.update_current_position()
    ProgressBar:
      size_hint_y: 0.20
      max: int(app.servo.maxSpeed)
      value: int(abs(app.servo.speed))

  Button:
    width: self.height
    size_hint_x: None
    font_name: "fonts/iosevka-regular.ttf" if root.is_running else "fonts/Font Awesome 6 Free-Solid-900.otf"
    text: "Next" if root.is_running else "\uf013"
    font_size: self.height / 4
    halign: "center"
    on_release:
      root.open_settings()
      # root.open_settings() if root.is_running else root.open_settings()