<AssistedThreadingScreen>:
  BoxLayout:
    title: "Assisted Threading Settings"
    orientation: "vertical"
    padding: 10
    ScreenHeader:
      text: "Assisted Threading Settings"

    ScrollView:
      do_scroll_x: False
      do_scroll_y: True
      GridLayout:
        id: grid_layout
        cols: 1
        spacing: 1
        size_hint_y: None
        height: self.minimum_height

        TitleItem:
          name: "Scales Settings"
        DropDownItem:
          id: saddle_dropdown
          height: 60
          name: "Saddle Scale"
          options: root.get_saddle_scale_options()
          value: root.get_label_for_scale_id(root.assistedThreadingBar.selected_saddle_scale_id) if root.assistedThreadingBar else ""
          on_value: root.on_saddle_scale_selected(self.value)
        DropDownItem:
          id: cross_slide_dropdown
          height: 60
          name: "Cross Slide Scale"
          options: root.get_cross_slide_scale_options()
          value: root.get_label_for_scale_id(root.assistedThreadingBar.selected_cross_slide_scale_id) if root.assistedThreadingBar else ""
          on_value: root.on_cross_slide_scale_selected(self.value)

        TitleItem:
          name: "Speeds and Distance Settings"
        NumberItem:
          name: "Reversing Speed (Steps/s)"
          value: root.assistedThreadingBar.reversing_speed
          on_value: root.set_reversing_speed(self.value)
        NumberItem:
          name: "Encoder sync tolerance (Steps)"
          value: root.assistedThreadingBar.encoder_sync_tolerance
          on_value: root.assistedThreadingBar.encoder_sync_tolerance = self.value
        BooleanItem:
          name: "Metric Distances"
          value: root.assistedThreadingBar.metric_distances
          on_value: root.assistedThreadingBar.metric_distances = self.value
        NumberItem:
          name: "Saddle backlash retraction distance (MM)" if root.assistedThreadingBar.metric_distances else "Saddle backlash retraction distance (IN)"
          value: root.assistedThreadingBar.backlash_retraction_distance
          on_value: root.assistedThreadingBar.backlash_retraction_distance = int(self.value)
        NumberItem:
          name: "Saddle backlash cushion (MM)" if root.assistedThreadingBar.metric_distances else "Saddle backlash cushion (IN)"
          value: root.assistedThreadingBar.backlash_cushion
          on_value: root.assistedThreadingBar.backlash_cushion = int(self.value)